apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "ditiss0019@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "Devopsproject@321"
type: Opaque

# Passw0rd@1234